services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: js-api-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/usr/src/app
      # Keep container's node_modules from being shadowed by the host bind mount
      - /usr/src/app/node_modules
    command: npm run dev